### ISSUE TITLE
Getting the Alpha Code

### ISSUE THREAD

**Issue by webzest** [PiranhaCMS/piranha.core.blog#2]
Hi, 

Thank you for your reply on my other question concerning getting a blog to work on an existing .NET 2.1.  I would like to try your suggestion and install the 5.1 alpha1 code.  Can you please tell me how to install the Alpha1 into my DOTNET and use the template?

**Comment by tidyui** [comment]
The alpha packages are available as pre-release packages on NuGet. As long as you include pre-releases you should be able to upgrade the packages in your existing project! You only need the template if you want to create an empty blog for reference. Installation instructions are available on its NuGet Page.

/Håkan
